### ISSUE TITLE
Breaks with analyzer 5.0.0

### ISSUE THREAD

**Issue by nullrocket** [6thsolution/dart_sealed#15]
Running ```dart run build_runner build``` with a dependency on analyzer v5.0.0 gives the following errors.  Dropping back to 4.7.0 works fine.

``` console

../../../../.pub-cache/hosted/pub.dartlang.org/sealed_generators-1.13.0/lib/src/manifest/manifest_reader_builder.dart:40:12: Error: The getter 'isEnum' isn't defined for the class 'ClassElement'.
 - 'ClassElement' is from 'package:analyzer/dart/element/element.dart' ('../../../../.pub-cache/hosted/pub.dartlang.org/analyzer-5.0.0/lib/dart/element/element.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'isEnum'.
      !cls.isEnum && !cls.isMixin && !cls.isMixinApplication,
           ^^^^^^
../../../../.pub-cache/hosted/pub.dartlang.org/sealed_generators-1.13.0/lib/src/manifest/manifest_reader_builder.dart:40:27: Error: The getter 'isMixin' isn't defined for the class 'ClassElement'.
 - 'ClassElement' is from 'package:analyzer/dart/element/element.dart' ('../../../../.pub-cache/hosted/pub.dartlang.org/analyzer-5.0.0/lib/dart/element/element.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'isMixin'.
      !cls.isEnum && !cls.isMixin && !cls.isMixinApplication,
                          ^^^^^^^
../../../../.pub-cache/hosted/pub.dartlang.org/sealed_generators-1.13.0/lib/src/manifest/manifest_reader.dart:148:28: Error: The getter 'element' isn't defined for the class 'DartType'.
 - 'DartType' is from 'package:analyzer/dart/element/type.dart' ('../../../../.pub-cache/hosted/pub.dartlang.org/analyzer-5.0.0/lib/dart/element/type.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'element'.
    final reference = type.element;
                           ^^^^^^^

```

**Comment by ride4sun** [comment]
![image](https://user-images.githubusercontent.com/7740651/209973715-491fe939-f0da-4803-b82b-f9bf019b92c3.png)

I am just wanted to migrade from super_enum and it seems like I can not get this library to run the generator successfully



[INFO] Precompiling build script......
[WARNING] /C:/Users/ride4/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/sealed_generators-1.13.0/lib/src/manifest/manifest_reader_builder.dart:40:12: Error: The getter '
isEnum' isn't defined for the class 'ClassElement'.
 - 'ClassElement' is from 'package:analyzer/dart/element/element.dart' ('/C:/Users/ride4/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/analyzer-5.2.0/lib/dart/element/el
ement.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'isEnum'.
      !cls.isEnum && !cls.isMixin && !cls.isMixinApplication,
           ^^^^^^
/C:/Users/ride4/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/sealed_generators-1.13.0/lib/src/manifest/manifest_reader_builder.dart:40:27: Error: The getter 'isMixin' i
sn't defined for the class 'ClassElement'.
 - 'ClassElement' is from 'package:analyzer/dart/element/element.dart' ('/C:/Users/ride4/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/analyzer-5.2.0/lib/dart/element/el
ement.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'isMixin'.

**Comment by ilyachange** [comment]
Same. Waiting for update...
