### ISSUE TITLE
Mention to ignore generated files on .gitignore and analysis_options.yaml

### ISSUE THREAD

**Issue by SaeedMasoumi** [6thsolution/dart_sealed#5]
It is worth mentioning to exclude generated files in the README.md:

For .gitignore:
```
*.sealed.dart
```
For analysis_options.yaml
```
analyzer:
  exclude:
    - **.sealed.dart
```

**Comment by FatulM** [comment]
Hi,
I think it should be added to our convention repository !?
And I don't think excluding files from analyzer is a good idea.

**Comment by SaeedMasoumi** [comment]
No for general use. 
What is the point of analyzing generated code?

Also, this kind of documentation is a suggestion to let users know how they can do that.

**Comment by FatulM** [comment]
Ok
I'll add this for next release

**Comment by FatulM** [comment]
I've added this to master branch documentation,
It will be published with next version
